# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = language_summary
SUB_SRC_FILES = \
    ch01_lan_intro.xml \
    ch02_script_lan.xml \
    ch02s2_word_vba.xml \
    ch02s3_excel_vba.xml \
    ch02s4_javascript.xml \
    ch02s5_php.xml \
    ch02s6_linux_shell.xml \
    ch02s7_windows_bat.xml \
    ch03_uppper_lan.xml \
    ch04_web_lan.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk